baseURL = "https://illion-atomic.netlify.app/"
languageCode = "ja"
title = "アート　オブ　アトミックチェス"
copyright = "Illion 2017-2020"

[params]
    author = "Original articles by Illion, 日本語 by al4th"
	footer = "&copy; [Illion](https://lichess.org/@/Illion) 2017-2020, &copy; [al4th](https://lichess.org/@/al4th) 2021 (日本語) | Theme by [Marken Foo](https://github.com/Marken-Foo/atom-site)"

[permalinks]
    post = "/:year/:month/:day/:slug/"
	timeless = "/:slug/"
	
[taxonomies]
	category = "categories"
	series = "series"
	tag = "tags"
	
[[menu.main]]
    name = "ホーム"
	url = "/"
	weight = 1
[[menu.main]]
    name = "このブログについて"
	url = "/about/"
	weight = 2
[[menu.main]]
    name = "アトミックのルール"
	url = "/atomic-rules/"
	weight = 3
[[menu.main]]
    name = "ブログ"
	url = "/categories/blog/"
	weight = 4
[[menu.main]]
	name = "戦略の教科書"
	url = "/resources/"
	weight = 5
[[menu.main]]
    name = "リンク"
	url = "/links/"
	weight = 6
	
